import { zip, of, interval } from 'rxjs';
const s1$ = of(1, 2, 3);
const s2$ = of(4, 5, 6, 7);
const s3$ = interval(1000);
const s$ = zip(s1$, s2$);
const m$ = zip(s3$, s2$);
const t$ = zip(s1$, s2$, s3$, (...a) => a.join(''));
//s$.subscribe(console.log);
// m$.subscribe(console.log);
t$.subscribe(console.log);
